name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Hoặc 'master', tùy vào branch bạn deploy

concurrency:
  group: pages-deploy
  cancel-in-progress: true  # Hủy các build cũ nếu có build mới

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Đảm bảo đúng thư mục build
